blogging/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from Blog.views import *
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  
                  #######New Blog #######
                  path('', newhome, name='home'),
                  path('single_post/<int:bid>/', newsingle_post, name='single'),
                  path('about_us/', newabout_us, name='about'),
                  path('blog/<int:bid>/', BlogDetails, name='blog'),
                  path('blog_comment/<int:bid>/', addcomment, name='comment'),
                  path('blog_like/<int:bid>/', LikeBlog, name='like'),
                  path('signup/', NewSignup, name='signup'),
                  path('logout/', Logout, name='logout'),
                  path('login/', NewLogin, name='newlogin'),
                  path('add_blog/', NewAddBlog, name='addblog'),
                  path('cat_detail/<int:cid>/', NewCategory_detail, name='cat_detail'),
                  path('allblogs/', NewAllblogs, name='allblog'),
                  path('edit_blog/<int:bid>/', NewEdit_blog, name='edit_blog'),
                  path('delete_blog/<int:bid>/', Delete_blog, name="delete_blog")
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models

from django.contrib.auth.models import User


# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    mobile = models.CharField(max_length=13)
    address = models.TextField()
    branch = models.CharField(max_length=50, default="CS")
    roll_no = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class BlogModel(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50, null=True)
    desc = models.TextField(null=True)
    date = models.DateField(null=True)
    long_desc = models.TextField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.title + " -- " + self.cat.name


class Like(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.usr.first_name


class UserComments(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE, null=True)
    msg = models.TextField(null=True)
    date = models.DateField(null=True)

    def __str__(self):
        return self.usr.first_name + " -- " + self.blog.title


class UserDetail(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=100, null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.usr.first_name

Blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import *
from datetime import date

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.

def Logout(request):
    logout(request)
    return redirect('home')


def newhome(request):
    allblog = BlogModel.objects.all()

    categorys = Category.objects.all()
    blog = allblog[::-1]
    print(blog)
    last_five_blog = blog[:5]
    print(last_five_blog)
    d = {'allblog': allblog, 'last_five_blog': last_five_blog, 'category': categorys}
    return render(request, 'newtemp/index.html', d)


def newsingle_post(request, bid):
    allblog = BlogModel.objects.all()
    blog = allblog[::-1]

    last_five_blog = blog[:7]
    d = {'allblog': allblog, 'last_five_blog': last_five_blog}
    return render(request, 'newtemp/single-post.html', d)


def newabout_us(request):
    return render(request, 'newtemp/about-us.html')


def BlogDetails(request, bid):
    data = BlogModel.objects.get(id=bid)
    categorys = Category.objects.all()
    allblog = BlogModel.objects.all()
    blog = allblog[::-1]
    last_five_blog = blog[:5]
    d = {'details': data, 'category': categorys, 'last_five_blog': last_five_blog, 'allblog': allblog}
    return render(request, 'newtemp/single-post.html', d)


def addcomment(request, bid):
    if not request.user.is_authenticated:
        return redirect('login')
    blogdata = BlogModel.objects.get(id=bid)
    usr = request.user
    td = date.today()
    msg = request.POST['message']
    UserComments.objects.create(usr=usr, blog=blogdata, date=td, msg=msg)
    return redirect('blog', bid)


def NewLogin(request):
    if request.method == "POST":
        dic = request.POST
        u = dic['user']
        p = dic['pwd']
        user = authenticate(username=u, password=p)
        if user:
            login(request, user)
            if request.user.is_staff:
                return redirect('home')
            return redirect('home')
        else:
            messages.error(request, 'User not found')
            return redirect('newlogin')
    return render(request, 'newtemp/login.html')


def NewSignup(request):
    error = False
    if request.method == "POST":
        d = request.POST
        fullname = d['user'].split()
        first = fullname[0]
        last = fullname[1]
        mobile = d['mobile']
        email = d['email']
        username = d['username']
        pwd = d['pwd']
        image = request.FILES['img']
        user = User.objects.filter(username=username)
        if user:
            error = True
        else:
            userdata = User.objects.create_user(username=username, password=pwd, email=email
                                                , first_name=first, last_name=last)
            UserDetail.objects.create(usr=userdata, image=image, mobile=mobile)
            return redirect('newlogin')
    dic = {"error": error}
    return render(request, 'newtemp/signup.html', dic)


def LikeBlog(request, bid):
    blogdata = BlogModel.objects.get(id=bid)
    user = request.user
    data = Like.objects.filter(blog=blogdata, usr=user)
    if not data:
        Like.objects.create(blog=blogdata, usr=user)
    else:
        data.delete()
    return redirect('blog', bid)


def NewAddBlog(request):
    if not request.user.is_authenticated:
        return redirect('newlogin')
    allcat = Category.objects.all()
    d = {'allcat': allcat}
    if request.method == "POST":
        dic = request.POST
        catid = dic['cat']
        catdata = Category.objects.get(id=catid)
        title = dic['title']
        short = dic['short']
        long = dic['long']
        img = request.FILES['img']
        today_date = date.today()
        userdata = request.user
        BlogModel.objects.create(usr=userdata, cat=catdata, title=title, desc=short, long_desc=long, date=today_date,
                                 image=img)
        return redirect('home')

    return render(request, 'newtemp/addblog.html', d)


def NewCategory_detail(request, cid):
    catdata = Category.objects.get(id=cid)
    blogs = BlogModel.objects.filter(cat=catdata)
    d = {'blogs': blogs}
    return render(request, 'newtemp/categoryDetails.html', d)


def NewAllblogs(request):
    allblogs = BlogModel.objects.all()
    # latest_blog = allblogs[::-1]
    latest_blog = BlogModel.objects.last()
    d = {'allblogs': allblogs, 'latest_blog': latest_blog}
    return render(request, 'newtemp/allblogs.html', d)


def NewEdit_blog(request, bid):
    blogdata = BlogModel.objects.get(id=bid)
    allcat = Category.objects.all()
    if request.method == "POST" and not request.user.is_staff:
        dic = request.POST
        catid = dic['cat']
        t = dic['title']
        short = dic['short']
        long = dic['long']

        try:
            img = request.FILES['img']
            blogdata.image = img
            blogdata.save()
        except:
            pass
        catdata = Category.objects.get(id=catid)
        blogdata.title = t
        blogdata.desc = short
        blogdata.long_desc = long
        blogdata.cat = catdata
        blogdata.save()

    d = {'blogdata': blogdata, 'allcat': allcat}
    return render(request, 'newtemp/edit_blog.html', d)


def Delete_blog(request, bid):
    details = BlogModel.objects.get(id=bid)
    details.delete()
    return redirect('home')

Blog/templates/newtemp/about-us.html
{% extends 'newtemp/base.html' %}
{% load static %}
{% block body %}
    <!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <img src="{% static 'img/core-img/breadcrumb-line.png' alt="">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">About</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->

    <div class="about-us-area section-padding-0-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-10">
                    <div class="section-heading">
                        <h2>About Me</h2>
                        <p> Enthusiastic Programmer</p>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-12 col-lg-10">
                    <div class="about-content">
                        <img src="{% static 'img/profile.jpeg' %}" style=" width:75% height:10%" alt="">
                        <p>Studying  Computer Science at KLE Dr M.S.Sheshgiri Engineering College Belagavi.</p>
                        <p>Just a demo project on Django Framework on Blogging Website</p><blockquote>
                            <h5>“It’s harder to read code than to write it.” </h5>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </div>

   {% endblock %}

Blog/templates/newtemp/addblog.html
{% extends 'newtemp/base.html' %}
{% load static %}
{% block body %}
    <!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <img src="img/core-img/breadcrumb-line.png" alt="">

                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->

<!-- ##### Contact Area Start ##### -->
    <section class="contact-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="contact-content-area">
                        <div class="row">
                            <div class="col-12 col-lg-3"></div>
                            <div class="col-12 col-lg-6">
                                <div class="contact-content">
                                    <h4>Create Blog </h4>

                                    <!-- Contact Form Area -->
                                    <div class="contact-form-area">
                                        <form action="" method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="col-12 col-lg-9">
													<div class="form-group">
                                                         <select name="cat" >
                                                        <option>Select Category</option>
                                                            {% for i in allcat %}
                                                            <option value="{{i.id}}">{{i.name}}</option>
                                                             {% endfor %}
                                                        </select>
                                                    </div>
												</div>

                                            <div class="row">
                                                <div class="col-12 col-lg-9">
													<div class="form-group">
                                                        <input type="text" class="form-control" name="title" placeholder="Title">
                                                    </div>
												</div>
												 <div class="col-12 col-lg-9">
													<div class="form-group">
                                                        <textarea class="form-control" name="short" placeholder="Short Description" ></textarea>
													</div>
												 </div>
													 <div class="col-12 col-lg-9">
														<div class="form-group">
                                                        	<textarea class="form-control" name="long" placeholder="Long Description" ></textarea>
                                                    	</div>
                                                	</div>
													 <div class="col-12 col-lg-9">
														<div class="form-group">
                                                        	<input type="file" class="form-control" name="img" placeholder="Image">
                                                    	</div>
                                                	</div>
                                                <div class="col-12">
                                                    <button type="submit" class="btn foode-btn">Create Blog</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->

    {% endblock %}

Blog/templates/newtemp/index.html
{% extends 'newtemp/base.html' %}
{% load static %}
{% block body %}
    <!-- ##### Hero Area Start ##### -->
    <section class="hero-area">
        <div class="hero-post-slides owl-carousel">
            {% for i in allblog %}
            <!-- Single Hero Post -->
            <div class="single-hero-post">
                <!-- Post Image -->
                <div class="slide-img bg-img" style="background-image:url({{i.image.url}});" ></div>
                <!-- Post Content -->
                <div class="hero-slides-content">
                    <p>{{ i.date }}</p>
                    <a href="{% url 'blog' i.id %}" class="post-title">
                        <h4>{{ i.title }}.</h4>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

    <!-- ##### Hero Area End ##### -->


    <!-- ##### Blog Content Area Start ##### -->
    <section class="blog-content-area section-padding-100">
        <div class="container">


            <div class="row justify-content-center">
                <!-- Blog Posts Area -->
                <div class="col-12 col-lg-8">
                    <div class="blog-posts-area">

                        <!-- Single Blog Post -->
                        <div class="single-blog-post d-flex flex-wrap mt-50">
                            <!-- Thumbnail -->
                            {% for i in last_five_blog %}
                            <div class="post-thumbnail mb-50">
                                <a href="{% url 'blog' i.id %}"><img src="{{ i.image.url }}" alt=""></a>
                            </div>
                            <!-- Content -->
                            <div class="post-content mb-50">
                                <p class="post-date">{{ i.date }}</p>
                                <a href="{% url 'blog' i.id %}" class="post-title">
                                    <h4>{{ i.title }}</h4>
                                </a>
                                <div class="post-meta">
                                    <a href="{% url 'blog' i.id %}"><span>by</span> {{ i.usr.first_name }}</a>

                                </div>
                                <p class="post-excerpt">{{ i.desc }}.</p>
                                <a href="{% url 'blog' i.id %}" class="read-more-btn">Continue Reading <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
                            </div>
                            <!-- Post Curve Line -->
                            <img class="post-curve-line" src="{% static 'img/core-img/post-curve-line.png' %}" alt="">
                            {% endfor %}
                        </div>
                    </div>

                    <!-- Pager -->
                    
                </div>

                <!-- Blog Sidebar Area -->
                <div class="col-12 col-sm-9 col-md-6 col-lg-4">
                    <div class="post-sidebar-area">

                        <!-- ##### Single Widget Area ##### -->
                        <div class="single-widget-area mt-0">
                            <!-- Title -->
                            <div class="widget-title">
                                <h6>Categories</h6>
                            </div>
                            <ol class="foode-catagories">
                                {% for i in category %}
                                <li><a href="#"><span><i class="fa fa-stop" aria-hidden="true"></i>{{ i.name }}</span> <span>({{ i.blogmodel_set.count }})</span></a></li>
                                {% endfor %}
                            </ol>
                        </div>

                        <!-- ##### Single Widget Area ##### -->
                        <div class="single-widget-area">
                            <!-- Title -->
                            <div class="widget-title">
                                <h6>Subscribe &amp; Follow</h6>
                            </div>
                            <!-- Widget Social Info -->
                            <div class="widget-social-info text-center">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-rss"></i></a>
                            </div>
                        </div>

                        <!-- ##### Single Widget Area ##### -->
                        <div class="single-widget-area">
                            <!-- Title -->
                            <div class="widget-title">
                                <h6>Latest Posts</h6>
                            </div>

                            <!-- Single Latest Posts -->
                            {% for i in last_five_blog %}
                            <div class="single-latest-post d-flex">

                               <div class="post-thumb">
                                    <img src="{{ i.image.url }}" alt="">
                               </div>
                                <div class="post-content">
                                    <a href="#" class="post-title">
                                        <h6>{{ i.title }}</h6>
                                    </a>
                                    <a href="#" class="post-author"><span>by</span> {{ i.usr.first_name }}</a>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                        <!-- ##### Single Widget Area ##### -->
                      
                    </div>
                </div>
            </div>
        </div>
    </section>
    </section>
    <!-- ##### Blog Content Area End ##### -->
{% endblock %}

Blog/templates/newtemp/single-post.html
{% extends 'newtemp/base.html' %}
{% load static %}
{% block body %}

    <!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <img src="{% static 'img/core-img/breadcrumb-line.png' %}" alt="">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Blog List</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Blog Single</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->

    <!-- ##### Blog Content Area Start ##### -->
    <section class="blog-content-area section-padding-0-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Blog Posts Area -->
                <div class="col-12 col-lg-8">
                    {% for i in allblog %}
                    {% if i.usr.id == request.user.is_authenticated %}
                      <a href="{% url 'edit_blog' details.id  %}" class="btn foode-btn btn-sm">EDIT blog</a>
                    <a href="{% url 'delete_blog' i.id %}" class="btn foode-btn btn-sm">DELETE blog</a>
                    <br></br>
                    {% endif %}
                    {% endfor %}
                    <div class="blog-posts-area">

                        <!-- Post Details Area -->
                        <div class="single-post-details-area">
                            <div class="post-thumbnail mb-30">
                                <img src="{{ details.image.url }}" style="width:800px ; height:500px;" alt="">
                            </div>
                            <div class="post-content">
                                <p class="post-date">{{ details.date }}</p>
                                <h4 class="post-title">{{ details.title }}</h4>
                                <div class="post-meta">
                                    <a href="#"><span>by </span>{{ details.usr.first_name}}</a>
                                    <a href="{% url 'like' details.id  %}"><i class="fa fa-heart" aria-hidden="true"></i>{{ details.like_set.count }}</a>
                                    <a href="#"><i class="fa fa-comments"></i>{{ details.usercomments_set.count }}</a>
                                </div>

                                <p>{{ details.long_desc}}</p>
                            </div>
                        </div>

                        <!-- Related Post Area -->
                        <div class="related-posts clearfix">
                            <!-- Line -->
                            <div class="curve-line bg-img mb-50" style="background-image: url(img/core-img/breadcrumb-line.png' %});"></div>

                            <div class="row">

                                <!-- Single Blog Post -->
                                <div class="col-12 col-md-6">
                                    <div class="single-blog-post related-post">
                                        <div class="post-content mb-50">
                                        </div>
                                    </div>
                                </div>

                                <!-- Single Blog Post -->
                                <div class="col-12 col-md-6">
                                    <div class="single-blog-post related-post">
                                        <!-- Thumbnail -->
                                        <div class="post-thumbnail mb-50">
                                        </div>
                                        <!-- Content -->
                                        <div class="post-content mb-50">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Line -->
                            <div class="curve-line bg-img" style="background-image: url(img/core-img/breadcrumb-line.png' %});"></div>
                        </div>

                        <!-- Comment Area Start -->
                        <div class="comment_area clearfix">
                            <h4 class="headline">{{ details.usercomments_set.count }} Comments</h4>

                            <ol>
                                <!-- Single Comment Area -->
                                {% for i in details.usercomments_set.all %}
                                <li class="single_comment_area">
                                    <div class="comment-wrapper d-flex">
                                        <!-- Comment Meta -->
                                        <div class="comment-author">
                                            <img src="{{ i.usr.userdetail_set.first.image.url }}" alt="">
                                        </div>
                                        <!-- Comment Content -->
                                        <div class="comment-content">
                                            <span class="comment-date">{{ i.date }}</span>
                                            <h5>{{ i.usr.first_name }}</h5>
                                            <p>{{ i.msg }}</p>
                                            <a href="#">Like</a>

                                        </div>
                                    </div>

                                </li>
                                {% endfor %}
                            </ol>
                        </div>

                        <!-- Leave A Comment -->
                        {% if request.user.is_authenticated %}
                        <div class="leave-comment-area clearfix">
                            <div class="comment-form">
                                <h4 class="headline">Leave A Comment</h4>

                                <!-- Comment Form -->
                                <form action="{% url 'comment' details.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="row">

                                        <div class="col-12">
                                            <div class="form-group">
                                                <textarea class="form-control" name="message" id="message" cols="30" rows="10" placeholder="Comment"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <button type="submit" class="btn foode-btn">Post Comment</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>

                <!-- Blog Sidebar Area -->
                <div class="col-12 col-sm-9 col-md-6 col-lg-4">

                    <div class="post-sidebar-area">

                        <!-- ##### Single Widget Area ##### -->
                        <div class="single-widget-area mt-0">
                            <!-- Title -->
                            <div class="widget-title">
                                <h6>Categories</h6>
                            </div>
                            <ol class="foode-catagories">
                                {% for i in category %}
                                <li><a href="{% url 'cat_detail' i.id %}"><span><i class="fa fa-stop" aria-hidden="true"></i>{{ i.name }}</span> <span>({{ i.blogmodel_set.count }})</span></a></li>
                                {% endfor %}
                            </ol>
                        </div>

                        <!-- ##### Single Widget Area ##### -->
                        <div class="single-widget-area">
                            <!-- Title -->
                            <div class="widget-title">
                                <h6>Latest Posts</h6>
                            </div>

                            <!-- Single Latest Posts -->
                             {% for i in last_five_blog %}
                            <div class="single-latest-post d-flex">

                               <div class="post-thumb">
                                    <img src="{{ i.image.url }}" alt="">
                               </div>
                                <div class="post-content">
                                    <a href="#" class="post-title">
                                        <h6>{{ i.title }}</h6>
                                    </a>
                                    <a href="#" class="post-author"><span>by</span> {{ i.usr.first_name }}</a>
                                </div>

                            </div>
                             {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Blog Content Area End ##### -->

    {% endblock %}